var data = [
    {
        "name": "Vera",
        "phone": "138-955-8109",
        "email": "eu.odio@maurisblanditmattis.ca",
        "birthday": "2015-07-18",
        "zip": "467025",
        "salary": 787197,
        "country": "Bahamas",
        "city": "Serrungarina",
        "company": "Suspendisse Dui Fusce PC",
        "type": 2
    },
    {
        "name": "Autumn",
        "phone": "369-405-2973",
        "email": "Quisque@loremsemper.com",
        "birthday": "2014-05-03",
        "zip": "370659",
        "salary": 168857,
        "country": "Suriname",
        "city": "Eigenbrakel",
        "company": "Nibh Dolor Nonummy LLC",
        "type": 9
    },
    {
        "name": "Amy",
        "phone": "693-6192",
        "email": "sit@egetmagnaSuspendisse.ca",
        "birthday": "2015-08-06",
        "zip": "2794",
        "salary": 235913,
        "country": "Cocos (Keeling) Islands",
        "city": "Chartres",
        "company": "Tincidunt Consulting",
        "type": 1
    },
    {
        "name": "Thor",
        "phone": "569-6512",
        "email": "parturient.montes.nascetur@imperdietnon.edu",
        "birthday": "2014-01-17",
        "zip": "26962",
        "salary": 853938,
        "country": "Spain",
        "city": "Beho",
        "company": "Nulla LLC",
        "type": 10
    },
    {
        "name": "Dakota",
        "phone": "270-477-0444",
        "email": "sed.pede@tortordictumeu.edu",
        "birthday": "2015-06-17",
        "zip": "7374PU",
        "salary": 575048,
        "country": "Bonaire, Sint Eustatius and Saba",
        "city": "Yahyalı",
        "company": "Parturient Montes Nascetur Inc.",
        "type": 1
    },
    {
        "name": "Cooper",
        "phone": "610-9420",
        "email": "placerat.Cras.dictum@eratVivamus.net",
        "birthday": "2015-07-20",
        "zip": "73706",
        "salary": 170683,
        "country": "New Caledonia",
        "city": "Deline",
        "company": "Nulla Tincidunt Neque Ltd",
        "type": 2
    },
    {
        "name": "Bethany",
        "phone": "949-378-7845",
        "email": "erat@Morbiaccumsanlaoreet.edu",
        "birthday": "2014-12-16",
        "zip": "83245-257",
        "salary": 998642,
        "country": "Poland",
        "city": "Milwaukee",
        "company": "Vel Sapien Company",
        "type": 1
    },
    {
        "name": "Ronan",
        "phone": "503-6165",
        "email": "pellentesque@egestasDuisac.co.uk",
        "birthday": "2015-03-23",
        "zip": "1124",
        "salary": 38416,
        "country": "Aruba",
        "city": "Calgary",
        "company": "Donec PC",
        "type": 7
    },
    {
        "name": "Lamar",
        "phone": "244-4542",
        "email": "enim.sit@nonarcu.com",
        "birthday": "2015-07-29",
        "zip": "18214",
        "salary": 106591,
        "country": "Palau",
        "city": "Portland",
        "company": "Tristique Pharetra Quisque Corp.",
        "type": 4
    },
    {
        "name": "Gisela",
        "phone": "203-196-7156",
        "email": "porttitor.tellus@Sed.org",
        "birthday": "2014-03-20",
        "zip": "587048",
        "salary": 255047,
        "country": "Italy",
        "city": "Aberystwyth",
        "company": "Augue Eu Tempor Associates",
        "type": 6
    },
    {
        "name": "Nolan",
        "phone": "694-889-2611",
        "email": "Etiam.laoreet.libero@Aliquamadipiscing.ca",
        "birthday": "2014-07-10",
        "zip": "74-869",
        "salary": 205358,
        "country": "Gambia",
        "city": "Coldstream",
        "company": "Ac Fermentum Vel PC",
        "type": 7
    },
    {
        "name": "Echo",
        "phone": "623-969-3747",
        "email": "enim@volutpatNulla.edu",
        "birthday": "2015-04-27",
        "zip": "M1K 9P9",
        "salary": 986701,
        "country": "Congo, the Democratic Republic of the",
        "city": "Genk",
        "company": "A Industries",
        "type": 9
    },
    {
        "name": "Lamar",
        "phone": "409-746-2980",
        "email": "aliquam.iaculis.lacus@nonmassa.edu",
        "birthday": "2015-09-16",
        "zip": "2945",
        "salary": 669021,
        "country": "Latvia",
        "city": "Victoria",
        "company": "Donec Nibh Enim Corp.",
        "type": 3
    },
    {
        "name": "Myles",
        "phone": "459-4494",
        "email": "ultrices@bibendumDonec.com",
        "birthday": "2015-01-21",
        "zip": "70105",
        "salary": 507894,
        "country": "Dominica",
        "city": "Pradamano",
        "company": "Vitae Company",
        "type": 6
    },
    {
        "name": "Nevada",
        "phone": "829-7145",
        "email": "vitae.semper@magnisdisparturient.com",
        "birthday": "2014-10-18",
        "zip": "43365",
        "salary": 383814,
        "country": "Zambia",
        "city": "Alkmaar",
        "company": "Accumsan Neque LLP",
        "type": 3
    },
    {
        "name": "Alec",
        "phone": "948-240-3163",
        "email": "turpis@feugiat.com",
        "birthday": "2015-12-07",
        "zip": "46466",
        "salary": 302711,
        "country": "Sao Tome and Principe",
        "city": "Montacuto",
        "company": "Est Tempor Industries",
        "type": 1
    },
    {
        "name": "Jacqueline",
        "phone": "781-5902",
        "email": "augue.eu@In.net",
        "birthday": "2014-03-26",
        "zip": "T6R 8V7",
        "salary": 428665,
        "country": "Macao",
        "city": "Forge-Philippe",
        "company": "Nunc Pulvinar PC",
        "type": 5
    },
    {
        "name": "Iola",
        "phone": "750-600-5040",
        "email": "elit.fermentum.risus@velarcueu.ca",
        "birthday": "2015-06-02",
        "zip": "3100HW",
        "salary": 237198,
        "country": "Samoa",
        "city": "Hubli",
        "company": "Non Sapien Molestie Corp.",
        "type": 4
    },
    {
        "name": "Chanda",
        "phone": "814-399-7586",
        "email": "eleifend.nunc@uteratSed.co.uk",
        "birthday": "2015-04-18",
        "zip": "4495PB",
        "salary": 969237,
        "country": "Thailand",
        "city": "Aklavik",
        "company": "Aliquet Incorporated",
        "type": 3
    },
    {
        "name": "Angela",
        "phone": "604-375-3105",
        "email": "tincidunt.dui.augue@dolorsitamet.edu",
        "birthday": "2014-10-30",
        "zip": "39591",
        "salary": 781312,
        "country": "Panama",
        "city": "Wilhelmshaven",
        "company": "Id Sapien Cras LLC",
        "type": 9
    },
    {
        "name": "Lillian",
        "phone": "261-724-3915",
        "email": "pharetra@leoelementum.edu",
        "birthday": "2015-09-10",
        "zip": "71205",
        "salary": 246633,
        "country": "Denmark",
        "city": "Enines",
        "company": "Nunc Interdum Corporation",
        "type": 10
    },
    {
        "name": "Judah",
        "phone": "167-773-1211",
        "email": "massa.rutrum.magna@dis.com",
        "birthday": "2015-02-08",
        "zip": "630178",
        "salary": 107709,
        "country": "Grenada",
        "city": "Inuvik",
        "company": "Mauris Sit Amet Corporation",
        "type": 7
    },
    {
        "name": "Stacey",
        "phone": "306-9282",
        "email": "sagittis@facilisisfacilisismagna.net",
        "birthday": "2014-11-29",
        "zip": "RC3A 1YB",
        "salary": 68433,
        "country": "Saint Helena, Ascension and Tristan da Cunha",
        "city": "Evere",
        "company": "Dictum Eu Placerat Institute",
        "type": 1
    },
    {
        "name": "Caryn",
        "phone": "833-6570",
        "email": "nec.luctus.felis@atliberoMorbi.org",
        "birthday": "2015-07-21",
        "zip": "00383",
        "salary": 369536,
        "country": "Slovenia",
        "city": "Gloucester",
        "company": "Suspendisse Ac Metus Foundation",
        "type": 7
    },
    {
        "name": "Blythe",
        "phone": "127-257-0096",
        "email": "dictum@quispedeSuspendisse.org",
        "birthday": "2015-05-28",
        "zip": "64142",
        "salary": 580272,
        "country": "Denmark",
        "city": "Issime",
        "company": "Auctor Ltd",
        "type": 2
    },
    {
        "name": "Oren",
        "phone": "469-5672",
        "email": "odio.sagittis@facilisismagnatellus.net",
        "birthday": "2014-11-25",
        "zip": "41971-540",
        "salary": 26096,
        "country": "Morocco",
        "city": "Duisburg",
        "company": "Pellentesque Sed Industries",
        "type": 3
    },
    {
        "name": "Jaden",
        "phone": "612-420-8900",
        "email": "eu.nibh@nec.org",
        "birthday": "2015-10-31",
        "zip": "52888",
        "salary": 614459,
        "country": "Saint Kitts and Nevis",
        "city": "Ajmer",
        "company": "Ut Inc.",
        "type": 9
    },
    {
        "name": "Galena",
        "phone": "165-417-1952",
        "email": "molestie.sodales.Mauris@Cum.ca",
        "birthday": "2015-09-11",
        "zip": "878376",
        "salary": 102245,
        "country": "Zimbabwe",
        "city": "Alert Bay",
        "company": "Pede Cum Sociis Limited",
        "type": 1
    },
    {
        "name": "Bianca",
        "phone": "477-4812",
        "email": "semper.erat@dignissim.edu",
        "birthday": "2014-06-09",
        "zip": "200530",
        "salary": 362786,
        "country": "Pakistan",
        "city": "Moorsele",
        "company": "Tortor At Inc.",
        "type": 10
    },
    {
        "name": "Zephr",
        "phone": "878-284-3761",
        "email": "Donec@arcuSedeu.co.uk",
        "birthday": "2014-07-02",
        "zip": "4637",
        "salary": 776370,
        "country": "Liberia",
        "city": "Melsele",
        "company": "Quam Vel Sapien Corp.",
        "type": 4
    },
    {
        "name": "Ashely",
        "phone": "714-2602",
        "email": "elit@hendreritneque.net",
        "birthday": "2015-01-28",
        "zip": "5262",
        "salary": 145093,
        "country": "American Samoa",
        "city": "Sunshine Coast Regional District",
        "company": "Nulla Industries",
        "type": 1
    },
    {
        "name": "Cody",
        "phone": "894-210-2707",
        "email": "Quisque.ac.libero@necorci.org",
        "birthday": "2014-11-11",
        "zip": "40497",
        "salary": 202141,
        "country": "Palau",
        "city": "Kamarhati",
        "company": "Scelerisque Mollis Phasellus LLC",
        "type": 3
    },
    {
        "name": "Uriah",
        "phone": "252-631-3725",
        "email": "laoreet.lectus@aliquetdiamSed.ca",
        "birthday": "2014-02-07",
        "zip": "03526",
        "salary": 834569,
        "country": "British Indian Ocean Territory",
        "city": "Town of Yarmouth",
        "company": "A Institute",
        "type": 4
    }
];
