-- jdbc.properties 의 jdbc.url 이 가리키는 MySQL 스키마용 DDL.
-- 서버 기동 시 AiAgentMenuSchemaInitializer 가 자동 실행한다 (CREATE TABLE IF NOT EXISTS).
-- 수동 적용: mysql ... epro < src/main/resources/META-INF/sql/epro/V1__ai_agent_menu.sql

CREATE TABLE IF NOT EXISTS T_AI_AGENT_MENU_SNAPSHOT (
    SECTION_CD   VARCHAR(16)  NOT NULL COMMENT 'SCM | PILOT',
    MENU_JSON    LONGTEXT     NOT NULL COMMENT '모듈·링크 JSON 배열',
    UPDATED_AT   DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (SECTION_CD)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='SCM AI Agent 메뉴 최종 스냅샷';

CREATE TABLE IF NOT EXISTS T_AI_AGENT_MENU_EVENT (
    EVENT_SEQ    BIGINT       NOT NULL AUTO_INCREMENT COMMENT '이벤트 일련번호',
    SECTION_CD   VARCHAR(16)  NOT NULL,
    EVENT_TYP    VARCHAR(32)  NOT NULL COMMENT 'MODULE_ADD|MODULE_EDIT|MODULE_DEL|LINK_ADD|LINK_EDIT|LINK_DEL',
    MODULE_ID    VARCHAR(64)  NULL,
    LINK_ID      VARCHAR(64)  NULL,
    OLD_JSON     VARCHAR(4000) NULL,
    NEW_JSON     VARCHAR(4000) NULL,
    ACTOR_ID     VARCHAR(100) NULL,
    CREATED_AT   DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (EVENT_SEQ),
    KEY IX_AI_MENU_EVT_SEC_TM (SECTION_CD, CREATED_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='SCM AI Agent 메뉴 변경 이벤트';
